# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolyFromPointsLines
                                 A QGIS plugin
 This plugin builds polygons from a points and lines layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-14
        copyright            : (C) 2019 by Alessandro Frigeri
        email                : alessandro.frigeri@inaf.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PolyFromPointsLines class from file PolyFromPointsLines.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .polygen import PolyFromPointsLines
    return PolyFromPointsLines(iface)
